apiVersion: v2
kubeVersion: ">= 1.26.0"
name: portal-pathogen
description: Helm Chart for the portal-pathogen frontend application
type: application
version: 1.6.2
appVersion: "1.6.2"
icon: https://avatars.githubusercontent.com/u/55493511?s=200&v=4
